### ISSUE TITLE
Make fails - aff.c for loop C99 error

### ISSUE THREAD

**Issue by firmcorp** [sleuthkit/sleuthkit#855]
Trying to build v4.4.1 from source, I have compiled libewf (latest) and tried various versions of AFF .. 

Having a hell of a time with make, see below !!  Tried adding c99 setting to the MakeFile for AFF and Sleuth, neither seemed to fix this problem.

Is this an AFF problem, or a Sleuth problem ? Please tell me if I should redirect this issue elsewhere.

HELP

aff.c: In function ‘aff_close’:
aff.c:219:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < img_info->num_img; i++) {
  ^
aff.c:219:2: note: use option -std=c99 or -std=gnu99 to compile your code
make[3]: *** [aff.lo] Error 1

**Comment by bcarrier** [comment]
Thanks. It's fixed with #851 in develop branch. Should be part of the 4.4.2 release in early July.

**Comment by mx-pycoder** [comment]
Hello,

Not sure if I should report this here or open a new issue, but the build still fails on this issue in the 4.4.2 release:
`
aff.c: In function ‘aff_close’:
aff.c:219:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0; i < img_info->num_img; i++) {
  ^
aff.c:219:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
`
